version: 0.2

env:
  shell: bash

phases:
   build:
    commands:
    - aws cloudformation create-change-set \
    --stack-name dbb-myapp-stack \
    --change-set-name my-change-set \
    --change-set-type CREATE \
    --template-body file://app.yaml \
    --capabilities CAPABILITY_IAM